---
- name: Create node_exporter directory
  file:
    path: "{{ node_exporter_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Get node_exporter
  unarchive:
    src: "{{ node_exporter_link }}"
    dest: "{{ node_exporter_dir }}"
    remote_src: True
    extra_opts: "--strip=1"

- name: Copy node_exporter service file
  template:
    src: node_exporter.service.j2
    dest: "{{ systemd_dir }}/node_exporter.service"
    owner: root
    group: root
    mode: 0644
  notify: node_exporter restart

